### ISSUE TITLE
Nits

### ISSUE THREAD

**Issue by vr8hub** [weijia-cheng/ernest-howard-crosby_captain-jinks-hero#1]
- [x] Semanticate adds an "eoc" to the dedication initials that I believe is correct.
- [x] Modernize spelling corrects a few `reenforcements` in chapters 10-11 that are correct. If you're running the plain 2.2 version of the tools, there is a bug that turns it into `rinforcements`; that's been corrected but not released, so if need be you can change them manually to reinforcements.
- [x] "Onward, Christian Soldiers" should be tagged as a song, i.e. se:name.music.song.
- [x] I would think "Cap" should be tagged as an abbreviation, since it's described as one?
- [x] The paragraph starting "Why, the Light Brigade…" in chapter 14 should have `class="continued"` on it. Same for "Which reading is correct?", "There is nothing difficult…" and "For some reason…".

**Comment by weijia-cheng** [comment]
~I am pretty confident "Onward, Christian Soldiers" (and this parodied version) should be tagged as a hymn--just look at how many hits it has at [hymnary.org](https://hymnary.org/text/onward_christian_soldiers_marching_as)! I am not sure about the first point so I'll post that in the group for Alex to look at.~

Oh, I see, this is referring to the actual title. OK, I can do that, though I was under the impression tagging unitalicized titles is not super necessary.

**Comment by vr8hub** [comment]
Oh, OCS is definitely a hymn, but we don’t have a hymn semantic for the name of a hymn.

**Comment by vr8hub** [comment]
To clarify (I realize a little late): I’m not talking about the block quote, I’m talking about the name of it in quotes just before the blockquote, i.e. the “Onward Christian Soldiers”.

**Comment by vr8hub** [comment]
There are several things we semanticate that are quoted rather than italicized: poems that aren't epics, songs, essays, short-stories, etc. If one of our vocabularies has the semantics, we typically semanticate it.
